import Navbar from "@/components/Navbar";
import "./globals.css";
import { CartProvider } from "@/context/CartProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <CartProvider>
        <body>
          <Navbar />
          {children}
        </body>
      </CartProvider>
    </html>
  );
}
